# Generated by Django 4.1.1 on 2022-10-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('details', models.TextField(null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '1. Course Creator',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '2. Training Course Categories',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(null=True, upload_to='course_img/')),
                ('technologies', models.TextField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='training.coursecreator')),
                ('trainingcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcoursecategory')),
            ],
            options={
                'verbose_name_plural': '3. Training Courses',
            },
        ),
    ]
