# Generated by Django 4.1.1 on 2022-10-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='trainingcategory',
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_courses', to='training.coursecreator'),
        ),
        migrations.DeleteModel(
            name='TrainingCourseCategory',
        ),
    ]
