# Generated by Django 4.1.1 on 2022-10-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0001_initial'),
        ('training', '0003_studentcourseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training_student', to='eLearning.student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training', to='training.trainingcourse')),
            ],
            options={
                'verbose_name_plural': '6. Enrolled Trainings',
            },
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
    ]
