# Generated by Django 4.1.1 on 2022-10-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0001_initial'),
        ('training', '0004_studenttrainingenrollment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecreator',
            options={'verbose_name_plural': '0. Course Creator'},
        ),
        migrations.AlterModelOptions(
            name='studenttrainingenrollment',
            options={'verbose_name_plural': '2. Enrolled Trainings'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'verbose_name_plural': '1. Training Courses'},
        ),
        migrations.CreateModel(
            name='TrainingCourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('reviews', models.TextField(null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning.student')),
            ],
            options={
                'verbose_name_plural': '3. Training Course Rating',
            },
        ),
    ]
