# Generated by Django 4.1.1 on 2022-10-22 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_trainingcourserating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourserating',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
