# Generated by Django 4.1.1 on 2022-10-30 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_alter_chapter_options_alter_course_options_and_more'),
        ('training', '0007_alter_trainingcourserating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTrainingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('f_time', models.TimeField(verbose_name='Time')),
                ('t_time', models.TimeField(null=True, verbose_name='Time')),
                ('meeting_link', models.URLField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning.teacher')),
            ],
            options={
                'verbose_name_plural': '4. Training Details',
            },
        ),
    ]
