# Generated by Django 4.1.1 on 2022-10-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_coursetrainingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourseRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('rec_video', models.FileField(upload_to='training_recording/')),
                ('rec_date', models.DateField(verbose_name='Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
            ],
            options={
                'verbose_name_plural': '5. Training Csurse Recordings',
            },
        ),
    ]
