# Generated by Django 4.1.1 on 2022-10-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_trainingcourserecording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetrainingdetails',
            old_name='course',
            new_name='training_course',
        ),
        migrations.RenameField(
            model_name='studenttrainingenrollment',
            old_name='training',
            new_name='training_course',
        ),
        migrations.RenameField(
            model_name='trainingcourserating',
            old_name='course',
            new_name='training_course',
        ),
        migrations.RenameField(
            model_name='trainingcourserecording',
            old_name='course',
            new_name='training_course',
        ),
    ]
