# Generated by Django 4.1.1 on 2022-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_rename_course_coursetrainingdetails_training_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourserecording',
            name='rec_note',
            field=models.FileField(default=None, upload_to='training_notes/'),
        ),
        migrations.AddField(
            model_name='trainingcourserecording',
            name='rec_time',
            field=models.TimeField(default=None, verbose_name='Time'),
        ),
    ]
