# Generated by Django 4.1.1 on 2022-10-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_trainingcourserecording_rec_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourserecording',
            name='rec_number',
            field=models.PositiveIntegerField(default=None, max_length=20),
        ),
    ]
