# Generated by Django 4.1.1 on 2022-10-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_alter_chapter_options_alter_course_options_and_more'),
        ('training', '0012_trainingcourserecording_rec_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTrainingDetails',
            new_name='TrainingTrainingDetails',
        ),
        migrations.AlterField(
            model_name='trainingcourserecording',
            name='rec_number',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
