# Generated by Django 4.1.1 on 2022-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_rename_coursetrainingdetails_trainingtrainingdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourserecording',
            name='rec_note',
            field=models.FileField(upload_to='training_notes/'),
        ),
        migrations.AlterField(
            model_name='trainingcourserecording',
            name='rec_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
