# Generated by Django 4.1.1 on 2022-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0003_alter_studentcourseenrollment_options'),
        ('training', '0014_alter_trainingcourserecording_rec_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttrainingenrollment',
            options={'verbose_name_plural': '2. Student Training Enrollment'},
        ),
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_topic', models.CharField(max_length=150)),
                ('s_time', models.TimeField(verbose_name='Time')),
                ('s_date', models.DateField(verbose_name='Date')),
                ('s_meet_link', models.URLField(null=True)),
                ('s_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning.teacher')),
                ('s_training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcourse')),
            ],
            options={
                'verbose_name_plural': '5. Training Session',
            },
        ),
    ]
