# Generated by Django 4.1.1 on 2022-10-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_alter_studenttrainingenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsessions',
            options={'verbose_name_plural': '6. Training Session'},
        ),
        migrations.AddField(
            model_name='trainingsessions',
            name='s_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
