# Generated by Django 4.1.1 on 2022-10-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_alter_trainingsessions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessions',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
