# Generated by Django 4.1.1 on 2022-10-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_remove_trainingsessions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtrainingdetails',
            name='meeting_link',
        ),
    ]
