# Generated by Django 4.1.1 on 2022-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '6. Student Course Enrollment'},
        ),
    ]
