# Generated by Django 4.1.1 on 2022-11-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0005_teacherresume_delete_popularcourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherresume',
            options={'verbose_name_plural': '44. Teacher Resume'},
        ),
    ]
