# Generated by Django 4.1.1 on 2022-11-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0007_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
