# Generated by Django 4.1.1 on 2022-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0008_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag_line',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
