# Generated by Django 4.1.1 on 2023-02-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eLearning", "0012_student_profile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="qualification",
        ),
    ]
