# Generated by Django 4.1.1 on 2023-03-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0018_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='doc_file',
        ),
    ]
