# Generated by Django 4.1.1 on 2023-03-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0019_remove_studentassignment_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='doc_file',
            field=models.FileField(null=True, upload_to='Assignmnets/'),
        ),
    ]
