# Generated by Django 4.1.1 on 2023-04-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0024_attempquiz_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempquiz',
            name='quiz',
        ),
    ]
