# Generated by Django 4.1.1 on 2023-04-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0025_remove_attempquiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eLearning.quiz'),
        ),
    ]
