# Generated by Django 4.1.1 on 2023-04-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0028_alter_studymaterial_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='doc_file',
        ),
    ]
