# Generated by Django 4.1.1 on 2023-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0029_remove_studentassignment_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='student_status',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
