# Generated by Django 4.1.1 on 2022-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='socialgithub',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='sociallinekin',
            new_name='social_linkedin',
        ),
    ]
