# Generated by Django 4.1.1 on 2022-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_aboutus_social_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='social_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='social_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
