# Generated by Django 4.1.1 on 2022-09-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_featured_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '4. Chapter'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Students'},
        ),
    ]
