# Generated by Django 4.1.1 on 2022-10-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentclouseenrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClouseEnrollment',
            new_name='StudentCourseEnrollment',
        ),
    ]
