# Generated by Django 4.1.1 on 2022-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Rating'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='Note_file',
            field=models.FileField(null=True, upload_to='Chapter_notes'),
        ),
    ]
