# Generated by Django 4.1.1 on 2022-10-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_courserating_options_chapter_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='Note_file',
        ),
        migrations.CreateModel(
            name='TrainingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '8. Training Details',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='note_file',
            field=models.FileField(null=True, upload_to='Chapter_notes/'),
        ),
    ]
