# Generated by Django 4.1.1 on 2022-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_chapter_note_file_trainingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetails',
            name='meeting_link',
            field=models.URLField(null=True),
        ),
    ]
