# Generated by Django 4.1.1 on 2022-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trainingdetails_meeting_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdetails',
            name='chapter',
        ),
    ]
