# Generated by Django 4.1.1 on 2022-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_trainingdetails_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdetails',
            old_name='time',
            new_name='f_time',
        ),
        migrations.AddField(
            model_name='trainingdetails',
            name='t_time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
